# Generated by Django 2.2.6 on 2020-07-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='File type name')),
                ('code', models.CharField(max_length=30, verbose_name='File type code')),
                ('description', models.CharField(default='', max_length=200, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
