# Generated by Django 3.2.11 on 2022-01-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para_code', models.CharField(max_length=60, verbose_name='Parameter code')),
                ('descr', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description')),
                ('para_value', models.CharField(blank=True, max_length=1000, verbose_name='Parameter value')),
                ('para_group', models.CharField(blank=True, max_length=30, null=True, verbose_name='Parameter Group')),
                ('for_system', models.BooleanField(default=True)),
            ],
        ),
    ]
