# Generated by Django 3.2.11 on 2022-01-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_sysparameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codetable',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
