# Generated by Django 3.2.11 on 2022-01-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_codetable_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codetable',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
