# Generated by Django 3.2.11 on 2022-01-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_codetable_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codetable',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
