# Generated by Django 3.2.11 on 2022-03-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_codetable_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='symbol',
        ),
        migrations.AddField(
            model_name='currency',
            name='code',
            field=models.CharField(default=1, max_length=3, verbose_name='Currency code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codetable',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='codetable',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codetable',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
