# Generated by Django 3.2.11 on 2022-02-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserStateAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('initiated_by', models.TextField()),
                ('start_state', models.TextField()),
                ('end_state', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('ip_address', models.TextField()),
            ],
        ),
    ]
