# Generated by Django 3.2.11 on 2022-01-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionaction',
            name='next_action_date',
        ),
        migrations.RemoveField(
            model_name='collectionaction',
            name='next_action_type',
        ),
        migrations.RemoveField(
            model_name='collectionaction',
            name='next_attachment',
        ),
        migrations.RemoveField(
            model_name='collectionaction',
            name='next_reference',
        ),
        migrations.RemoveField(
            model_name='collectionaction',
            name='note',
        ),
    ]
