# Generated by Django 3.2.11 on 2022-01-26 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0002_auto_20220125_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionaction',
            name='action_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='InvoiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_numbre', models.IntegerField(blank=True, null=True)),
                ('order_number', models.CharField(blank=True, max_length=100, null=True)),
                ('order_unit_value', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('invoice_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('ord_trp_value', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('order_vnit_value_Curr', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('ord_trp_value_curr', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('invoice_amount_curr', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('is_reduce_vat', models.BooleanField(default=False)),
                ('invoice_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='sales.invoice')),
            ],
        ),
    ]
