# Generated by Django 3.2.11 on 2022-01-29 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_collectionaction_action_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionaction',
            name='is_legal_action',
        ),
        migrations.RemoveField(
            model_name='collectionaction',
            name='scheduler',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='is_legal_action',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='scheduler_name',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='status',
        ),
        migrations.RemoveField(
            model_name='scheduleritem',
            name='invoice',
        ),
        migrations.AlterField(
            model_name='collectionaction',
            name='action_type',
            field=models.CharField(blank=True, choices=[('call', 'Call'), ('chat', 'Chat'), ('offline_message', 'Offline message'), ('ticket', 'Ticket'), ('plan_follow_up', 'Plan Follow up')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleritem',
            name='scheduler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduler', to='sales.scheduler'),
        ),
    ]
