# Generated by Django 3.2.11 on 2022-01-29 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20220129_2236'),
        ('sales', '0008_alter_invoice_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulerinvoice',
            name='scheduler_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduler_invoice', to='sales.scheduleritem'),
        ),
        migrations.AlterField(
            model_name='scheduleritem',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_scheduler', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='scheduleritem',
            name='scheduler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_scheduler', to='sales.scheduler'),
        ),
    ]
