# Generated by Django 3.2.11 on 2022-01-30 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20220129_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleritem',
            name='is_legal_action',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='schedulerinvoice',
            name='scheduler_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduler_item', to='sales.scheduleritem'),
        ),
    ]
