# Generated by Django 3.2.11 on 2022-01-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20220130_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleritem',
            name='invoice',
            field=models.ManyToManyField(to='sales.Invoice'),
        ),
    ]
