# Generated by Django 3.2.11 on 2022-01-30 15:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0011_scheduleritem_invoice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollectionAction',
            new_name='CollectionActionReport',
        ),
        migrations.RemoveField(
            model_name='scheduleritem',
            name='invoice',
        ),
    ]
