# Generated by Django 3.2.11 on 2022-03-02 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0011_auto_20220129_2236'),
        ('sales', '0012_auto_20220130_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(blank=True, choices=[('call', 'Call'), ('email', 'Email'), ('chat', 'Chat'), ('offline_message', 'Offline message')], max_length=100, null=True)),
                ('action_status', models.CharField(choices=[('done', 'Processed'), ('due', 'Follow up'), ('finished', 'Finished')], default='pending', max_length=100)),
                ('action_date', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_legal', models.BooleanField(default=False)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actionreport_customer', to='customer.customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='schedulerinvoice',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='schedulerinvoice',
            name='scheduler_item',
        ),
        migrations.RemoveField(
            model_name='scheduleritem',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='scheduleritem',
            name='scheduler',
        ),
        migrations.AddField(
            model_name='scheduler',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_scheduler', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='invoice',
            field=models.ManyToManyField(to='sales.Invoice'),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='total_invoice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CollectionActionReport',
        ),
        migrations.DeleteModel(
            name='SchedulerInvoice',
        ),
        migrations.DeleteModel(
            name='SchedulerItem',
        ),
    ]
