# Generated by Django 3.2.11 on 2022-03-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_auto_20220302_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='company',
            new_name='customer',
        ),
    ]
