# Generated by Django 3.2.11 on 2022-03-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_rename_company_invoice_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='invoice',
            field=models.ManyToManyField(related_name='scheduler_invoice', to='sales.Invoice'),
        ),
    ]
