# Generated by Django 3.2.11 on 2022-03-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_alter_invoice_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionreport',
            name='invoice',
            field=models.ManyToManyField(related_name='actionreport_invoice', to='sales.Invoice'),
        ),
    ]
