# Generated by Django 3.2.11 on 2022-03-08 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20220308_1809'),
        ('sales', '0019_actionreport_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_customer', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_scheduler', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Scheduler Name'),
        ),
    ]
