# Generated by Django 3.2.11 on 2022-01-29 12:38

import api.models
import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_group', models.CharField(max_length=150)),
                ('content_name', models.CharField(max_length=150)),
                ('sequence', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Menu name')),
                ('url', models.CharField(max_length=1000, verbose_name='Url')),
                ('icon', models.CharField(max_length=500, verbose_name='Icon')),
                ('sequence', models.IntegerField(default=0, verbose_name='Sequence')),
                ('is_active', models.BooleanField(default=True)),
                ('menu_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Menu Code')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.mainmenu')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('theme', models.CharField(blank=True, max_length=15, null=True, verbose_name='Color')),
                ('display_row', models.IntegerField(blank=True, null=True, verbose_name='Display row')),
                ('default_page', models.TextField(blank=True, max_length=250, null=True, verbose_name='Default page loaded after login')),
                ('profile_image', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=api.models.get_profile_image_name)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usergroup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PagePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_name', models.CharField(max_length=30)),
                ('act_code', models.CharField(max_length=200)),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.contentpermission')),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.mainmenu')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
                ('page_permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.pagepermission')),
            ],
        ),
    ]
