# Generated by Django 3.2.11 on 2022-01-07 08:50

import api.models
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_group', models.CharField(max_length=150)),
                ('content_name', models.CharField(max_length=150)),
                ('sequence', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=5, null=True, verbose_name='Code')),
                ('has_state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_company', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.country', verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending')], max_length=50)),
                ('outstanding_amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('currency_outstanding_amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('invoice_created_on', models.DateTimeField(auto_now_add=True)),
                ('invoice_due_date', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Menu name')),
                ('url', models.CharField(max_length=1000, verbose_name='Url')),
                ('icon', models.CharField(max_length=500, verbose_name='Icon')),
                ('sequence', models.IntegerField(default=0, verbose_name='Sequence')),
                ('is_active', models.BooleanField(default=True)),
                ('menu_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Menu Code')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.mainmenu')),
            ],
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduler_name', models.CharField(max_length=200, verbose_name='Scheduler Name')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('call_due', 'Call due'), ('call_done', 'Call done'), ('finished', 'Finished'), ('legal_action', 'Legal Action')], max_length=100, null=True)),
                ('total_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduler_invoices', to='api.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('theme', models.CharField(blank=True, max_length=15, null=True, verbose_name='Color')),
                ('display_row', models.IntegerField(blank=True, null=True, verbose_name='Display row')),
                ('default_page', models.TextField(blank=True, max_length=250, null=True, verbose_name='Default page loaded after login')),
                ('profile_image', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=api.models.get_profile_image_name)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ManyToManyField(related_name='total_invoices', to='api.Invoice')),
                ('scheduler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduler_item', to='api.scheduler')),
            ],
        ),
        migrations.CreateModel(
            name='PagePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_name', models.CharField(max_length=30)),
                ('act_code', models.CharField(max_length=200)),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.contentpermission')),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.mainmenu')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
                ('page_permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.pagepermission')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(blank=True, choices=[('call', 'Call'), ('chat', 'Chat'), ('offline_message', 'Offline message'), ('ticket', 'Ticket'), ('plan_follow_up', 'Plan Follow up')], max_length=100, null=True)),
                ('action_date', models.DateTimeField()),
                ('summary', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment', models.TextField(default='')),
                ('is_legal_action', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('scheduler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_scheduler', to='api.scheduler')),
            ],
        ),
    ]
