# Generated by Django 3.2.11 on 2022-01-19 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220119_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduler',
            name='invoice',
        ),
    ]
