# Generated by Django 3.2.11 on 2022-01-20 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_remove_scheduler_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='collectionaction',
            name='next_action_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionaction',
            name='next_action_type',
            field=models.CharField(blank=True, choices=[('call', 'Call'), ('chat', 'Chat'), ('offline_message', 'Offline message'), ('ticket', 'Ticket'), ('plan_follow_up', 'Plan Follow up')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collectionaction',
            name='next_attachment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='collectionaction',
            name='next_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collectionaction',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='collectionaction',
            name='action_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Auditlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('action_on', models.DateTimeField(auto_now=True)),
                ('ip_addr', models.CharField(default='', max_length=45)),
                ('descr', models.TextField(default='')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.auditaction')),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
        ),
    ]
