# Generated by Django 3.2.11 on 2022-01-21 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220121_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduler',
            name='invoice',
        ),
    ]
