# Generated by Django 3.2.11 on 2022-01-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_scheduler_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='is_legal_action',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scheduleritem',
            name='invoice',
            field=models.ManyToManyField(related_name='scheduler_invoices', to='api.Invoice'),
        ),
    ]
