# Generated by Django 3.2.11 on 2022-01-22 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220122_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleritem',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduler_customer', to='api.customer'),
        ),
        migrations.AlterField(
            model_name='scheduleritem',
            name='invoice',
            field=models.ManyToManyField(related_name='scheduler_invoice', to='api.Invoice'),
        ),
    ]
