# Generated by Django 3.2.11 on 2022-01-25 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220122_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='action_by',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='collectionaction',
            name='action_by',
        ),
        migrations.RemoveField(
            model_name='collectionaction',
            name='scheduler',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='company',
        ),
        migrations.RemoveField(
            model_name='scheduleritem',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='scheduleritem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='scheduleritem',
            name='scheduler',
        ),
        migrations.DeleteModel(
            name='AuditAction',
        ),
        migrations.DeleteModel(
            name='Auditlog',
        ),
        migrations.DeleteModel(
            name='CollectionAction',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Scheduler',
        ),
        migrations.DeleteModel(
            name='SchedulerItem',
        ),
    ]
