# Generated by Django 3.2.11 on 2022-01-25 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('job_title', models.CharField(max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=5, null=True, verbose_name='Code')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec_customer_id', models.IntegerField(blank=True, null=True, verbose_name='EC customer Id')),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contact_person', models.CharField(default='', max_length=200)),
                ('contact_number', models.CharField(default='', max_length=200)),
                ('account_number', models.CharField(help_text='Number assigned by Accounting', max_length=30, null=True, verbose_name='Account number')),
                ('initials', models.CharField(blank=True, max_length=30, null=True)),
                ('vat_no', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_prefrence', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_postage', models.CharField(blank=True, max_length=100, null=True)),
                ('is_sales_review', models.BooleanField(default=False)),
                ('is_vat_verified', models.BooleanField(default=False)),
                ('peppol_address', models.CharField(blank=True, max_length=500, null=True)),
                ('last_order_date', models.DateTimeField()),
                ('is_allow_send_mail', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('is_exclude_vat', models.BooleanField(default=False)),
                ('is_deliver_invoice_by_post', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('is_peppol_verfied', models.BooleanField(default=False)),
                ('Is_always_vat', models.BooleanField(default=False)),
                ('is_teacher', models.BooleanField(default=False)),
                ('is_student_team', models.BooleanField(default=False)),
                ('is_call_report_attached', models.BooleanField(default=False)),
                ('account_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.contact', verbose_name='Account manager')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.country', verbose_name='Country')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.currency', verbose_name='Currency')),
                ('customer_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_type', to='base.codetable')),
                ('invoice_lang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_language', to='base.codetable')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.codetable')),
                ('tax_number_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taxt_number_type', to='base.codetable')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('is_power_user', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.contact')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.codetable')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.country')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(default='', max_length=100)),
                ('street_no', models.CharField(default='', max_length=100)),
                ('street_address1', models.CharField(default='', max_length=300)),
                ('street_address2', models.CharField(default='', max_length=300)),
                ('note', models.TextField(blank=True, null=True)),
                ('zip', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.CharField(blank=True, max_length=300, null=True)),
                ('other_state', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('box_no', models.CharField(blank=True, max_length=300, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.contact')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.country', verbose_name='Country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.user')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.codetable', verbose_name='State')),
            ],
        ),
    ]
