# Generated by Django 3.2.11 on 2022-01-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('sales', '0003_auto_20220126_1138'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='ECUser',
        ),
        migrations.RemoveField(
            model_name='address',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='address',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='create_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
