# Generated by Django 3.2.11 on 2022-01-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20220126_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='contact_number',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Is_always_vat',
            new_name='is_always_vat',
        ),
        migrations.RemoveField(
            model_name='address',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='fax',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='sa_company_competence',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='sa_ec_customer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
