# Generated by Django 3.2.11 on 2022-01-26 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('customer', '0003_auto_20220126_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='ec_contact_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_delivery', to='base.codetable'),
        ),
    ]
