# Generated by Django 3.2.11 on 2022-01-27 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_sysparameter'),
        ('customer', '0004_auto_20220126_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='create_on',
        ),
        migrations.AlterField(
            model_name='customer',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.currency', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_type', to='base.codetable'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='invoice_lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_language', to='base.codetable'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.codetable'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_number_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taxt_number_type', to='base.codetable'),
        ),
    ]
