# Generated by Django 3.2.11 on 2022-01-27 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_codetable_name'),
        ('customer', '0006_auto_20220127_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='address_type', to='base.codetable'),
        ),
    ]
