# Generated by Django 3.2.11 on 2022-01-28 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_codetable_name'),
        ('customer', '0007_address_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='ecuser',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.contact'),
        ),
        migrations.AlterField(
            model_name='ecuser',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.codetable'),
        ),
        migrations.AlterField(
            model_name='ecuser',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ecuser',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
