# Generated by Django 3.2.11 on 2022-01-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20220128_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street_address1',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address2',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
