# Generated by Django 3.2.11 on 2022-01-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20220129_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('is_power_user', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('sa_user_responsibilities', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ecuser',
            name='company',
        ),
        migrations.RemoveField(
            model_name='ecuser',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='ecuser',
            name='language',
        ),
    ]
