# Generated by Django 3.2.11 on 2022-03-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20220129_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='company',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='company',
            new_name='customer',
        ),
    ]
