# Generated by Django 3.2.11 on 2022-03-03 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20220302_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='company_name',
            new_name='name',
        ),
    ]
