# Generated by Django 3.2.11 on 2022-03-08 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220302_1730'),
        ('customer', '0013_rename_company_name_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ec_customer_id',
            field=models.IntegerField(verbose_name='EC customer Id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.contact'),
        ),
        migrations.AlterField(
            model_name='user',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.codetable'),
        ),
    ]
