# Generated by Django 3.2.11 on 2022-03-14 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20220308_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.contact'),
        ),
    ]
