# Generated by Django 3.2.11 on 2022-03-15 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_alter_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customer'),
        ),
    ]
