# Generated by Django 3.2.11 on 2022-03-15 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220302_1730'),
        ('customer', '0017_alter_user_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_type', to='base.codetable'),
        ),
    ]
